en:
  onboarding-dashboard:
    menu:
      # Text of navigation menu item
      new-hires-tab: "New-Hires"
      # Text of navigation menu item, "Content" here is in context of informational resources
      content-tab: "Content"
      # Text of navigation menu item, "Activities" here is in context of informational resources
      content-activities-tab: "Activities"
      # Text of navigation menu item, "Forms" here is in context of informational resources
      content-forms-tab: "Forms"
  
    new-hires:
      header: "New Hires"
      # amount of selected hires
      selected: "[NUMBER] selected"
      filter:
        status: Status
        office-location: Office Location
        more: More
      # search field
