es:
  onboarding-dashboard:
    menu:
      # Text of navigation menu item
      new-hires-tab: "Esta es otra"
      # Text of navigation menu item, "Content" here is in context of informational resources
      content-tab: "Contenidos"
      # Text of navigation menu item, "Activities" here is in context of informational resources
      content-activities-tab: "Actividades"
      # Text of navigation menu item, "Forms" here is in context of informational resources
      content-forms-tab: "formularios"
  
    new-hires:
      header: "Nuevas contrataciones"
      # amount of selected hires
      selected: "[NÚMERO] seleccionado"
      filter:
        status: Estado
        office-location: Localización de la oficina
        more: Más
      # search field
